#! /bin/sh

if ! pgrep -x "sxhkd" > /dev/null
then
    sxhkd&
fi

if ! pgrep -x "polybar" > /dev/null
then
    $HOME/.config/polybar/launch.sh
fi

xsetroot -cursor_name left_ptr &

bspc monitor DVI-I-1 -d       
# bspc monitor HDMI-0 -d III

bspc config border_width          1
bspc config window_gap            6
bspc config focus_follows_pointer true

bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config ignore_ewmh_focus     true
# bspc config history_aware_focus   true
bspc config honor_size_hints      false

bspc rule -a scratchpad state=floating sticky=on
bspc rule -a *:org-capture state=floating follow=on
bspc rule -a mpv-firefox desktop=^4 state=floating
# st -c scratchpad -e ~/bin/scratch &
