#! /bin/sh

if ! pgrep -x "sxhkd" > /dev/null
then
    sxhkd&
fi

reloadpolybar &

xsetroot -cursor_name left_ptr &

bspc monitor DVI-I-1 -d 1 2 3 4 9
bspc monitor HDMI-0 -d 5 6 7 8

bspc config border_width          2
bspc config window_gap            6
bspc config focus_follows_pointer true
bspc config focused_border_color #eceff4
bspc config normal_border_color #3b4252

bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config ignore_ewmh_focus     true
bspc config honor_size_hints      false

bspc rule -a scratchpad state=floating sticky=on
bspc rule -a mpv-firefox desktop=^4 state=floating
bspc rule -a mpv state=floating center=on
bspc rule -a Emacs:doom-capture state=floating
bspc rule -a Firefox desktop=^9
