theme = "rose_pine_dawn"

[editor]
auto-save = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-q" = ":quit"
"x" = ["extend_line_below", "extend_to_line_bounds"]
"X" = ["extend_line_above", "extend_to_line_bounds"]
"A-x" = ["extend_to_line_bounds", "trim_selections"]
"C-;" = ["flip_selections"]

[editor.lsp]
auto-signature-help = false
